# Generated by Django 5.2.1 on 2025-06-25 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('is_live', models.BooleanField(default=False, verbose_name='LIVE')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемые')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
    ]
