# Generated by Django 4.2.8 on 2025-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='achievements',
            field=models.TextField(blank=True, default='', help_text='Перечислите достижения через запятую'),
        ),
    ]
