# Generated by Django 4.2.8 on 2025-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_alter_coach_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='position',
            field=models.CharField(choices=[('head', 'Главный тренер'), ('assistant', 'Ассистент'), ('gk', 'Тренер вратарей'), ('fitness', 'Тренер по физподготовке'), ('analyst', 'Аналитик')], max_length=20),
        ),
    ]
