# Generated by Django 4.2.8 on 2025-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(choices=[('goalkeeper', 'Вратарь'), ('defender', 'Защитник'), ('midfielder', 'Полузащитник'), ('forward', 'Нападающий')], max_length=20, verbose_name='Позиция')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер')),
                ('photo', models.ImageField(blank=True, upload_to='academy/players/', verbose_name='Фото')),
                ('join_year', models.PositiveIntegerField(default=2025, verbose_name='Год в академии')),
                ('is_active', models.BooleanField(default=True, verbose_name='В составе')),
                ('height', models.PositiveIntegerField(verbose_name='Рост (см)')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес (кг)')),
                ('matches', models.PositiveIntegerField(default=0, verbose_name='Матчи')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Голы')),
                ('assists', models.PositiveIntegerField(default=0, verbose_name='Ассисты')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Игрок академии',
                'verbose_name_plural': 'Игроки академии',
                'ordering': ['number'],
            },
        ),
    ]
