# Generated by Django 5.2.1 on 2025-06-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_achievement_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-years']},
        ),
        migrations.AddField(
            model_name='career',
            name='assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='career',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='players.player'),
        ),
    ]
