# Generated by Django 5.2.1 on 2025-06-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_career_options_career_assists_career_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='tournament',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='year',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='players.player'),
        ),
    ]
